### PR TITLE
Tools

### PR DESCRIPTION
**Pull request by bleonard**
* move license-checker
* lerna updater

### CODE REVIEW

**Comment by bleonard** [comment]
something crazy happened with this branch. maybe the autoupdating somehow. investigating.
EDIT: looks like I branched off the google-sheets branch and had some of that in there. all is well.

**Comment by evantahler** [comment]
Check out https://app.circleci.com/pipelines/github/grouparoo/grouparoo/1084/workflows/ed9f4998-cf21-4d7f-8779-c3838b06cd65/jobs/6960

something odd happened with the licence checker. it's only checking it's own packages now, not the whole monorepo

**Comment by bleonard** [comment]
thanks! have to look at those paths. will fix asap.

**Comment by evantahler** [comment]
Nice!

Screen Shot 2020-04-02 at 5 42 37 PM

**Pull request merged**
