### PR TITLE
Check & Fix package versions with Syncpack

### PR DESCRIPTION
**Pull request by evantahler**
Keeping package versions in sync is annoying.  We change versions of our own packages (alpha releases) and our dependencies often.  Now you can keep your branches up-to-date with one handy command! 

At the root of the monorepo, after rebasing main into your branch:
* Check Package Versions with `pnpm run version-checker`
* Fix Package Versions with `pnpm run version-fixer`

This PR adds a test to our CI suite which will alert us if there are dependencies across the monorepo that do not have the same version. For example:

```
➜  grouparoo git:(syncpack) pnpm run version-checker

> @grouparoo/grouparoo@0.0.0 version-checker /Users/evan/workspace/grouparoo/grouparoo
> ./tools/version-checker/check

Checking package versions...

- @grouparoo/core 0.8.0-alpha.5
  0.8.0-alpha.5 in dependencies of @grouparoo/app-staging-community
  0.8.0-alpha.5 in dependencies of @grouparoo/app-staging-config
  0.8.0-alpha.5 in dependencies of @grouparoo/app-staging-enterprise
  0.8.0-alpha.5 in dependencies of @grouparoo/airtable
  0.8.0-alpha.2 in devDependencies of @grouparoo/airtable. // <----------------------------
  0.8.0-alpha.5 in devDependencies of @grouparoo/app-templates
```

Thanks https://github.com/JamieMason/syncpack!

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

### CODE REVIEW

**Comment by evantahler** [comment]
Conveniently, `@grouparoo/airtable` is using the wrong version of core at the moment 😓

**Comment by evantahler** [comment]
A failing example: https://app.circleci.com/pipelines/github/grouparoo/grouparoo/14054/workflows/6a3cc40a-d16a-4482-8acd-c03ee2452b6d/jobs/373255

**Comment by evantahler** [comment]
A passing example https://app.circleci.com/pipelines/github/grouparoo/grouparoo/14055/workflows/6b50a371-2218-47a9-8025-3419af1d816d/jobs/373345

**Review by bleonard — APPROVED** [review]
Nice. does it do all the dev dependencies too?

**Comment by evantahler** [comment]
Sure does!
Screen Shot 2022-01-06 at 8 29 31 PM

**Pull request merged**
