### PR TITLE
Log parser

### PR DESCRIPTION
**Pull request by bleonard**
## Change description

Quick tool to parse a Grouparoo log file and extract performance data.

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
❤️

Can you add a README with a little bit of the CSV example it creates?

**Comment by evantahler** [comment]
Looks like some rebase/merge shenangins...

**Comment by bleonard** [comment]
gross.

**Comment by evantahler** [comment]
But... the merge looks ok https://github.com/grouparoo/grouparoo/commit/252edff4920aa68720a68ef0c47db46da07179e3, so 🤷?

**Pull request merged**
