### PR TITLE
Set Google-Sheets reading rows limits

### PR DESCRIPTION
**Pull request by pauloouriques**
## Change description

This PR sets the Google-Sheets reading rows limits

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

### CODE REVIEW

**Comment by bleonard** [comment]
What's this mean - it could only do 600 at a time? But not 900?

**Comment by fabform** [comment]
This is handy to find google sheets id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by fabform** [comment]
Handy to locate google sheet id
[find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Review by bleonard — APPROVED** [review]
Looks good. Is `600` documented somewhere?

**Comment by pauloouriques** [comment]
> Looks good. Is `600` documented somewhere?

I'm changing this because this limitation is related to the offset.

**Review by bleonard — APPROVED** [review]

**Pull request merged**
