### PR TITLE
`/bin/timed_run` also makes exports

### LINKED ISSUE #2870: [Feature]: Performance Improvements
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Let's speed up the Grouparoo Application!

### Describe the solution you'd like.

_No response_

### Describe an alternate solution.

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by evantahler**
Our perf testing script should also make exports. `-l` is the logger destination.

### Development

- [x] Application changes have been tested appropriately

### Impact

- [x] Code follows company security practices and guidelines
- [x] Security impact of change has been considered
- [x] Performance impact of change has been considered
- [x] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [x] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

### CODE REVIEW

**Review by bleonard — COMMENTED** [review]
looks good. might want to add some `destinationGroupMemberships` to the logger desintaiton in the demo so those `newGroups` calculations are part of the timed run,

**Comment by evantahler** [comment]
> looks good. might want to add some `destinationGroupMemberships` to the logger desintaiton in the demo so those `newGroups` calculations are part of the timed run,

That shouldn't matter *too* much as we always calculate a record's groups after an import, so that time is accounted for in the test.  We are sending all the Records in the Profile model just to have a lot...

**Comment by bleonard** [comment]
> > looks good. might want to add some `destinationGroupMemberships` to the logger desintaiton in the demo so those `newGroups` calculations are part of the timed run,
> 
> That shouldn't matter _too_ much as we always calculate a record's groups after an import, so that time is accounted for in the test. We are sending all the Records in the Profile model just to have a lot...

kk. i'll make a story for later. makes me feel better to benchmark all the pieces. If that "what groups am in" is a N+1 or something, I'd rather catch it in the benchmark.

**Comment by bleonard** [comment]
Or it's faster to only calculate the Groups a destination cares about. That's a good story actually because some care about none

**Review by bleonard — APPROVED** [review]

**Pull request merged**
