### PR TITLE
Change max node version

### PR DESCRIPTION
**Pull request by vklimontovich**
16.0.0 is not the latest version of node, 16.8.0 is

### CODE REVIEW

**Comment by bleonard** [comment]
Thanks @vklimontovich - this PR  https://github.com/grouparoo/grouparoo/pull/2129 has a blocker that is preventing v16 from working fully in our setup.

**Comment by bleonard** [comment]
The one this PR changes is actually only for that development. It's possible that the one that `grouparoo init` does could be upgraded because it doesn't have those compile times issues. Maybe @evantahler ?

I think that would be this file: https://github.com/grouparoo/grouparoo/blob/main/cli/templates/package.json

**Comment by bleonard** [comment]
When it does work, I imagine we'll do `< 17`

**Comment by evantahler** [comment]
This sparked some research and I _think_ that all the built Grouparoo packages will run on node.js v16... we just can't build them with that version yet.  

https://github.com/grouparoo/grouparoo/pull/2270 replaces this PR

**Pull request closed without merging**
