### PR TITLE
Fix typos in destination config template files

### PR DESCRIPTION
**Pull request by seancdavis**
Found this while working on plugin documentation.

### CODE REVIEW

**Review by evantahler — APPROVED** [review]
Well... at least we were consistent!

**Comment by pedroslopez** [comment]
For whatever it's worth, I also noticed some plugins have the appId defined as `{{appId}}` and others have a direct string (e.g. "customerioApp") in the template. Not sure if when you generate it the appId is filled in...

**Comment by seancdavis** [comment]
@pedroslopez Can you point me to an example?

**Comment by pedroslopez** [comment]
> @pedroslopez Can you point me to an example?

@seancdavis 

Sendgrid plugin using `"sendgridApp"`
https://github.com/grouparoo/grouparoo/blob/d5b11372097fe4ad523c80d53ae37191b9747c63/plugins/%40grouparoo/sendgrid/public/templates/destination/%7B%7B%7Bid%7D%7D%7D.js.template#L8

Facebook plugin using `{{{appId}}}`
https://github.com/grouparoo/grouparoo/blob/d5b11372097fe4ad523c80d53ae37191b9747c63/plugins/%40grouparoo/facebook/public/templates/destination/%7B%7B%7Bid%7D%7D%7D.js.template#L8

**Comment by seancdavis** [comment]
Thanks @pedroslopez! Opened #1494 with some cleanup.

**Pull request merged**
