### PR TITLE
Fix typescript errors in dbt plugin

### PR DESCRIPTION
**Pull request by asdfryan**
## Change description

Without this, I ran into errors during installation:
Screen Shot 2022-01-20 at 3 44 13 PM

After this, installation succeeded:
Screen Shot 2022-01-20 at 3 45 03 PM

### Development

- [ ] Application changes have been tested appropriately

### Impact

- [ ] Code follows company security practices and guidelines
- [ ] Security impact of change has been considered
- [ ] Performance impact of change has been considered
- [ ] Possible migration needs considered (model migrations, config migrations, etc.)

Please explain any security, performance, migration, or other impacts if relevant:

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached where applicable.
- [ ] Relevant tags have been added to the PR (bug, enhancement, internal, etc.)

### CODE REVIEW

**Comment by evantahler** [comment]
Thanks for the fix! 

I'm very curious why we aren't seeing this issue locally or in CI.  Can you share your versions like below?

```
➜  grouparoo git:(main) node --version
v16.13.1
➜  grouparoo git:(main) npm --version
8.1.2
➜  grouparoo git:(main) pnpm --version
6.26.1
➜  grouparoo git:(main)) cd core
➜  core git:(main) ./node_modules/.bin/tsc --version
Version 4.5.4
```

**Comment by asdfryan** [comment]
> Thanks for the fix!
> 
> I'm very curious why we aren't seeing this issue locally or in CI. Can you share your versions like below?
> 
> ```
> ➜  grouparoo git:(main) node --version
> v16.13.1
> ➜  grouparoo git:(main) npm --version
> 8.1.2
> ➜  grouparoo git:(main) pnpm --version
> 6.26.1
> ➜  grouparoo git:(main)) cd core
> ➜  core git:(main) ./node_modules/.bin/tsc --version
> Version 4.5.4
> ```

Sure -- here are my versions:
```
asdfryan@Ryans-MacBook-Pro grouparoo % node --version
v16.13.1
asdfryan@Ryans-MacBook-Pro grouparoo % npm --version
pn8.1.2
asdfryan@Ryans-MacBook-Pro grouparoo % pnpm --version
6.27.1
asdfryan@Ryans-MacBook-Pro grouparoo % ./node_modules/.bin/tsc --version
Version 4.5.4
```

**Comment by evantahler** [comment]
Thanks for the info!

I was able to get myself in a similar situation by enabling `noImplicitAny` for that plugin, but not exactly the same problem.  You may want to reset your copy of the monorepo with `npm run nuke` (in the root directory) and try `pnpm install` again - there might be some bad symlinks or package links.

Either way, I've extended your work in https://github.com/grouparoo/grouparoo/pull/2844 and just gone ahead and turned on `noImplicitAny` for the dbt plugin and :D

**Comment by evantahler** [comment]
Closing in favor of https://github.com/grouparoo/grouparoo/pull/2844

**Pull request closed without merging**
